// Generated by dts-bundle-generator v9.5.1

export type SwearCallback<T, R> = (item: T, index: number, arr: readonly T[]) => R | Promise<R>;
export type SwearCb<T, R> = SwearCallback<T, R> | (T extends string ? RegExp : never);
export type ElemOf<T extends readonly any[]> = T extends readonly (infer E)[] ? E : never;
export type SwearArrayMethods<T extends readonly any[]> = {
	filter(cb: SwearCb<ElemOf<T>, boolean>): Swear<ElemOf<T>[]>;
	find(cb: SwearCb<ElemOf<T>, boolean>): Swear<ElemOf<T> | undefined>;
	findIndex(cb: SwearCb<ElemOf<T>, boolean>): Swear<number>;
	forEach(cb: SwearCallback<ElemOf<T>, any>): Swear<ElemOf<T>[]>;
	every(cb: SwearCb<ElemOf<T>, boolean>): Swear<boolean>;
	map<U>(cb: SwearCallback<any, U>): Swear<U[]>;
	some(cb: SwearCb<ElemOf<T>, boolean>): Swear<boolean>;
	reduce<U>(cb: (acc: U, item: ElemOf<T>, index: number, arr: readonly ElemOf<T>[]) => U | Promise<U>, initial: U): Swear<U>;
	reduce(cb: (acc: ElemOf<T>, item: ElemOf<T>, index: number, arr: readonly ElemOf<T>[]) => ElemOf<T> | Promise<ElemOf<T>>): Swear<ElemOf<T>>;
	reduceRight<U>(cb: (acc: U, item: ElemOf<T>, index: number, arr: readonly ElemOf<T>[]) => U | Promise<U>, initial: U): Swear<U>;
	reduceRight(cb: (acc: ElemOf<T>, item: ElemOf<T>, index: number, arr: readonly ElemOf<T>[]) => ElemOf<T> | Promise<ElemOf<T>>): Swear<ElemOf<T>>;
};
export type SwearProps<T> = {
	[K in Exclude<keyof T, "valueOf" | "toString">]: T[K] extends (...args: any[]) => infer R ? (...args: any[]) => Swear<Awaited<R>> : Swear<T[K]>;
};
export type Swear<T, M extends Record<string, any> = {}> = Promise<T> & (0 extends 1 & T ? SwearArrayMethods<any[]> & SwearProps<any> : [
	T
] extends [
	never
] ? SwearProps<string> : T extends (...args: infer A) => infer R ? (...args: A) => Swear<Awaited<R>, M> : T extends readonly any[] ? SwearArrayMethods<T> & SwearProps<T> : SwearProps<T>) & M;
export type SwearOptions<M extends Record<string, any> = {}> = M & {
	number?: Record<string, (value: number, ...args: any[]) => any>;
	string?: Record<string, (value: string, ...args: any[]) => any>;
	array?: Record<string, (value: any[], ...args: any[]) => any>;
};
declare function swear<T, M extends Record<string, any> = {}>(value: T, options?: SwearOptions<M>): Swear<Awaited<T>, M>;

export {
	swear as default,
};

export {};
