// Generated by dts-bundle-generator v9.5.1

export type SwearCallback<T, R> = (item: T, index: number, arr: readonly T[]) => R | Promise<R>;
export type SwearArrayMethods<T extends readonly any[]> = {
	filter(cb: SwearCallback<T[number], boolean>): Swear<Array<T[number]>>;
	find(cb: SwearCallback<T[number], boolean>): Swear<T[number] | undefined>;
	findIndex(cb: SwearCallback<T[number], boolean>): Swear<number>;
	forEach(cb: SwearCallback<T[number], any>): Swear<Array<T[number]>>;
	every(cb: SwearCallback<T[number], boolean>): Swear<boolean>;
	some(cb: SwearCallback<T[number], boolean>): Swear<boolean>;
	reduce<U = T[number]>(cb: (acc: U, item: T[number], index: number, arr: readonly T[number][]) => U | Promise<U>, initial?: U): Swear<U>;
	reduceRight<U = T[number]>(cb: (acc: U, item: T[number], index: number, arr: readonly T[number][]) => U | Promise<U>, initial?: U): Swear<U>;
};
export type SwearProps<T> = {
	[K in keyof T]: T[K] extends (...args: infer A) => infer R ? (...args: A) => Swear<Awaited<R>> : Swear<T[K]>;
};
export type Swear<T, M extends Record<string, any> = {}> = Promise<T> & (T extends readonly any[] ? SwearArrayMethods<T> & SwearProps<T> : SwearProps<T>) & M;
export type SwearOptions<M extends Record<string, any> = {}> = M & {
	number?: Record<string, (value: number, ...args: any[]) => any>;
	string?: Record<string, (value: string, ...args: any[]) => any>;
	array?: Record<string, (value: any[], ...args: any[]) => any>;
};
declare function swear<T extends (...args: any[]) => any, M extends Record<string, any> = {}>(fn: T, options?: SwearOptions<M>): (...args: Parameters<T>) => Swear<Awaited<ReturnType<T>>, M>;
declare function swear<T, M extends Record<string, any> = {}>(value: T, options?: SwearOptions<M>): Swear<Awaited<T>, M>;
declare function swear<R>(fn: (...args: any[]) => any, options?: SwearOptions<any>): R;
declare function swear<R>(value: any, options?: SwearOptions<any>): R;

export {
	swear as default,
};

export {};
